server:
  port: 9999
spring:
  profiles:
    active: dev
mybatis-plus:
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: dev.cheerfun.pixivic.web
logging:
  config: classpath:logback-${spring.profiles.active}.xml
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
encoder:
  secret: 生蚝QAQ只是一位兴趣使然的面向ACG编程人员(●'◡'●)ﾉ♥♥♥♥♥♥
  iteration: 20
  keylength: 256
jjwt:
  secret: 生蚝QAQ只是一位兴趣使然的面向ACG编程人员(●'◡'●)ﾉ♥♥♥♥♥♥
  expirationTime: 864000
  refreshInterval: 1800000