server:
  port: 8080
spring:
#  profiles:
#    active: oyster
  redis:
    database: 0
    host: armbian
    port: 6379
  datasource:
    url: jdbc:mysql://47.93.4.88:3306/pixivic-test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: linhao199741
    type: com.alibaba.druid.pool.DruidDataSource
    batch:
      job:
        enabled: false
#mybatis-plus:
#  configuration:
#    cache-enabled: true
#    map-underscore-to-camel-case: true
#  mapper-locations: classpath*:/ArtistMapper/*Mapper.xml
#  type-aliases-package: dev.cheerfun.pixivic.web
# logging:
  # config: classpath:logback-${spring.profiles.active}.xml
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
encoder:
  secret: 生蚝QAQ只是一位兴趣使然的面向ACG编程人员(●'◡'●)ﾉ♥♥♥♥♥♥
  iteration: 20
  keylength: 256
jjwt:
  secret: 生蚝QAQ只是一位兴趣使然的面向ACG编程人员(●'◡'●)ﾉ♥♥♥♥♥♥
  expirationTime: 864000
  refreshInterval: 1800000
pixiv:
  oauth:
    client_id: KzEZED7aC0vird8jWyHM38mXjNTY
    client_secret: W9JZoJe00qPvJsiyCGT3CCtC6ZUtdpKpzMbNlUGP
    refresh_token: 07FHA5xA6NkOIxIayqm3tZbJqxbypDJHrXguT7cazLI
    device_token: fb12e7c1945000850deb5f7001c02745
    config: D:\user2.json
logging:
  level:
    com:
      looedu:
        mapper: debug
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  type-handlers-package: dev.cheerfun.pixivic.common.handler