server:
  port: 8080
spring:
#  profiles:
  #    active: mac
  data:
    redis:
      repositories:
        enabled: false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  mail:
    host: mail
    username: admin@cheerfun.dev
    password: Cheerfun.dev
    protocol: smtp
    properties:
      mail:
        smtp:
          connectiontimeout: 99000
          timeout: 99000
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
    test-connection: true
    port: 465
  redis:
    jedis:
      pool:
        max-active: 16 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 16 # 连接池中的最大空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
    cluster:
      nodes:
        - redis-1:6379
        - redis-2:6379
        - redis-3:6379
        - redis-4:6379
    password: Cheerfun.dev
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: root
    password: root
    publisher-confirm-type:
  datasource:
    primary:
      jdbc_url: jdbc:mysql://mysql-biz:3306/pixivic?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      username: root
      password: Cheerfun.dev
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximumPoolSize: 30
      minimumIdle: 2
      idleTimeout: 28800
      connectionTimeout: 3000
      maxLifetime: 28800
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
    secondary:
      jdbc_url: jdbc:mysql://mysql-crawler:3306/pixivic?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      username: root
      password: Cheerfun.dev
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximumPoolSize: 40
      minimumIdle: 2
      idleTimeout: 28800
      connectionTimeout: 3000
      maxLifetime: 28800
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
  cache:
    caffeine:
      spec: maximumSize=4096,expireAfterAccess=1800s
    type: caffeine
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
jjwt:
  secret: 生蚝QAQ只是一位兴趣使然的面向ACG编程人员♥♥♥♥♥♥♥♥♥♥♥♥
  expirationTime: 172800
  refreshInterval: 432000000
pixiv:
  oauth:
    client_id: KzEZED7aC0vird8jWyHM38mXjNTY
    client_secret: W9JZoJe00qPvJsiyCGT3CCtC6ZUtdpKpzMbNlUGP
    device_token: fb12e7c1945000850deb5f7001c02745
  imageSavePath: /home/
saucenao:
  token:
    path: /home/PIC/saucenao.json
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  type-handlers-package: dev.cheerfun.pixivic.common.util.json
elasticsearch:
  ip: elasticsearch:9200
apiLog:
  path: /home/PIC/log
sensitiveWordList:
  path: /home/PIC/sensitive
ssh:
  configPath: /home/PIC/ssh.conf
sitemap:
  savePath: /home/PIC/sitemap
  remoteSavePath: /home/PIC/sitemap
graphicsMagick:
  path: /usr/bin/gm
nsfw:
  modelPath: /home/PIC/nsfw.299x299.h5
chacha20:
  key: 生蚝是位兴趣使然的OTAKU
  nonce: PIXIVICJUST4
  counter: 21
recaptcha:
  secret: 6Le5lOIZAAAAAI34bH_axfWScwcKFnxUBNbpe60d
TFServingServer:
  localhost:8501
oauth2:
  issuer: https://pix.ipv4.host
  authorizationEndpoint: https://pix.ipv4.host/oauth/authorize
  tokenEndpoint: https://pix.ipv4.host/oauth/token
  checkToken:
  userinfoEndpoint: https://pix.ipv4.host/user/me
review:
  path: /home/PIC/sensitive/政治类-反动词库.txt
verifiedAPI:
  secretId: AKID9GO4RsrMlSTTPnf3Yc7aH1ndWddDaKHppcQ
  secretKey: iNRRsAbupPjZwcjrmjCm1dMqh6t07v8uLs4Cml3W
  url: https://service-mlmeeiob-1256140209.ap-shanghai.apigateway.myqcloud.com/release/mobile/verify_real_name?idcard=
messageApi:
  endpoint: sms.ap-shanghai.tencentcloudapi.com
  secretId: AKIDBDxTUHQDNI1rStw2t1wgV4kCeqnV5A85
  secretKey: qkPpysWuFLciZAVaQ7kHYZMKU5T9Xcqp
  appid: 1400478972
  templateID: 858513
  sign: 御宅电波
rclone:
  path: /usr/bin/rclone
milvus:
  host: milvus
  port: 19530
cbir:
  server: https://cbir.pixivic.com
  imageTempPath: /home/temp
wx:
  mp:
    appId: wxba62cb763436c3f9
    secret: a6583b3bf26aa7214d94e723ad80d37b
    token: CheerfunDEV
    aesKey: X8SKEphLReI0reXKHCJtEcPSwaZROi0REUtXSFYHeeo
jdcloud:
  accessKeyId: 5A84A85CD2C0379657E1C8A6140A079C
  secretAccessKey: 93173B7EA351CB7E99D99C7D1E90E479